### ISSUE TITLE
Enable end-to-end encryption always enabled + server config global?

### ISSUE THREAD

**Issue by blaxer** [Skylar-Tech/node-red-contrib-matrix-chat#10]
No matter what I do when I create or edit a matrix server config if I uncheck the end-to-end encryption checkbox when I edit the server config again it is always checked.

Also, any way to make the server config global to the entire NR installation? Seems to be a server config per flow maybe so I am having to re-create the server config on every flow and subflow..

**Comment by skylord123** [comment]
> No matter what I do when I create or edit a matrix server config if I uncheck the end-to-end encryption checkbox when I edit the server config again it is always checked.

This is definitely a bug and I have a fix that will be out soon.

> Also, any way to make the server config global to the entire NR installation? Seems to be a server config per flow maybe so I am having to re-create the server config on every flow and subflow..

By default the server config should be global. I just tested it and can for sure assign my server from another flow. I wonder if the other errors you are hitting are making things act funny. Give it a shot after I push out the update for the first problem and let me know if it keeps happening.

Thanks :)

**Comment by skylord123** [comment]
@blaxer I just published `0.1.7` which fixes e2ee not disabling correctly. Let me know if you still have problems and I will reopen this.

**Comment by skylord123** [comment]
Nope, this is still a problem. Although the checkbox is working correctly now the setting isn't applying. Fixing this in the next release here soon.

**Comment by skylord123** [comment]
This is now fixed.
