### ISSUE TITLE
[FR] Get own events

### ISSUE THREAD

**Issue by wuast94** [Skylar-Tech/node-red-contrib-matrix-chat#109]
As mentioned in Chat, would be nice to have an toggle on the receive node to get own events entered in another client.

I logged in with my main matrix account and i get all events in nodered to me but not from me.

for completness:
![image](https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/assets/16965460/9745f98a-581b-441b-b636-d3e1d7d94217)

**Comment by skylord123** [comment]
@wuast94 this was released with v0.8.0. Can you try it out?

**Comment by wuast94** [comment]
oh now that you ask, a friend of mine and i have running the 0.8.0 version for over 2 month or so without any problems (just nodered downgrading to the release version with an update).

and yes this feature works exactly as intended, so thanks again for the great work and to see the 0.8.0 official released 😊

**Comment by skylord123** [comment]
Awesome, glad it's working well. Thanks for taking the time to respond. :+1:
