### ISSUE TITLE
Cannot obtain access token

### ISSUE THREAD

**Issue by CapricaBSG** [Skylar-Tech/node-red-contrib-matrix-chat#112]
Hello,

I cannot obtain an access token. On the backend its synapse and when I attempt to call it, it says 405 Method Not Allowed.

I do not know if this is an issue at my end or with the server. Looking at the source code it seems to call url + /matrix-chat/login, when I try to do a POST call the terminal it also returns a 405 error. I do not know what I am doing wrong. Thanks

**Comment by skylord123** [comment]
Are you logged into Node-RED with a user that has the `flows.write` permission?

Is Node-RED behind a reverse proxy?

**Comment by CapricaBSG** [comment]
Yes my user has flows.write, and node-red is currently running in home assistant as a docker container. 
v 1.3.5 of node-red and 0.7.1 of node-red-contrix-matrix-chat. 

I also used insomina to do a POST call to the same url, and it also says error 405

**Comment by CapricaBSG** [comment]
I have found out the error, for custom servers, e.g. test.org, its critical to append the matrix.test.org, it was specific to me
