### ISSUE TITLE
Can't receive messenges in Node Red, because - "Context global contains a circular reference that cannot be persisted"

### ISSUE THREAD

**Issue by ThomasKlesse** [Skylar-Tech/node-red-contrib-matrix-chat#116]
Hi,

I'm confused. I've searched many threads but haven't found an answer or a solution.
Sending messages to a Matrix room basically works fine.
But when receiving messages I get a "timeout" error that I don't understand:
"Context global contains a circular reference that cannot be persisted"

Do I need to change the ContextStorage option in Node Red and if so, how?

Currently I use this option:
...
contextStorage: {
  default: {
    module: 'localfilesystem'
  }
},
...

Thanks a lot
Thomas

**Comment by skylord123** [comment]
Can you try out the dev branch and see if this issue persists? v0.8.0 should resolve this issue. We now delete the matrix global variable before shutdown to prevent it from persisting.

Another way to fix this on the older version is to disable global access to the matrix client from the server config but if you are using that in function nodes this is not possible without breaking that functionality.

**Comment by skylord123** [comment]
@ThomasKlesse this should be fixed in the latest release. If it is not let me know and I will re-open this.
