### ISSUE TITLE
duplicate messages

### ISSUE THREAD

**Issue by cthompstone** [Skylar-Tech/node-red-contrib-matrix-chat#30]
Hi anyone know why, after awhile of running I start to get messages coming in on receive nodes duplicated?
I presume it must be because the node is somehow using 2 connections back to the matrix server.
If I restart node-red the problem goes away (for awhile).
It's not really a big deal, I just have to filter them and drop the 2nd message off.  However, it's not really how things should be.
Thanks

**Comment by skylord123** [comment]
I just did a test on my laptop. I ran node-red locally and had it connect to a matrix server. I then sent a chat message to the bot and it only came in once. I turned my wifi off and waited for the bot to notice it was offline then I reconnected to the wifi and sent another message and it only came in once..

The following questions should help us figure this out:
Is there anything in your log that helps explain what is going on?
What node-red version are you running?
Are you sure you are using `node-red-contrib-matrix-chat` (which is this module) and not `node-red-contrib-matrix` (which is the other available matrix client)?
