### ISSUE TITLE
Shared Secret Registration - Invalid Request Signature

### ISSUE THREAD

**Issue by mbelt** [Skylar-Tech/node-red-contrib-matrix-chat#33]
Requests to v1 registration endpoint are being returned 403.

Error from Synapse:
`method='POST' uri='/_synapse/admin/v1/register' clientproto='HTTP/1.0' site='8008'> SynapseError: 403 - HMAC incorrect`

**Comment by skylord123** [comment]
Are you running a self-hosted server or using the public matrix server (matrix.org)? This does not work with servers you do not administrate.

What happens when you go to this url in your browser? `<your_server>/_synapse/admin/v1/register` (use the same domain that the client is using)

**Comment by mbelt** [comment]
Self hosted matrix server, Synapse v1.43.0. Shared secret registration is enabled, tested working.
The GET that node-red-contrib-matrix-chat makes to /v1/register is successful, but the subsequent POST is 403. (Invalid HMAC)

I was able to get the Registration Node working after removing `"user_type": "bot"` from the payload.
[This file](https://github.com/matrix-org/synapse/blob/master/synapse/api/constants.py) is referenced in the help doc as source of truth for valid user_type, and I took away that valid options are None, "bot", and "support". The matrix [registration api doc](https://matrix-org.github.io/synapse/develop/admin_api/register_api.html) says otherwise, that valid options are "admin" and "notadmin". 

Haven't dug any further on what works / doesn't work.

**Comment by skylord123** [comment]
Yes you are right. The HMAC was being generated incorrectly. Looks like when I ported it from Python I missed the part that added the `user_type`.

I just fixed this and tested it with the `bot` `user_type` and it worked perfectly. I'll be deploying a new release today that will fix this.

Thanks for bringing this to my attention :)

**Comment by skylord123** [comment]
Just released `0.3.0` that fixes this. Give it another try and if the problem persists feel free to re-open the issue.
