### ISSUE TITLE
bad link - ping pong example goes to html json

### ISSUE THREAD

**Issue by 2114L3** [Skylar-Tech/node-red-contrib-matrix-chat#38]
ping pong `view JSON` goes to html example, expected ping pong example

```
### Respond to "ping" with "pong"

[View JSON](respond-to-html-with-html.json)
```
line 57:
https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/blob/25c92b787aaa9392a74c94731efca6df84943ed0/examples/README.md?plain=1#L57

should be 
```
[View JSON](respond-ping-pong.json)
```

**Comment by skylord123** [comment]
This will be fixed in the `0.4.0` release coming out today. Thanks!
