### ISSUE TITLE
Error sending image message TypeError: callback is not a function

### ISSUE THREAD

**Issue by hillbicks** [Skylar-Tech/node-red-contrib-matrix-chat#42]
Hey there,

first of all, fantastic addon for nodered! Makes life so much easier. Thank you for making this available

Now, while setting up the addon, I notice that I get error messages in the debug log as stated in the title:

`Error sending image message TypeError: callback is not a function`

The thing is, the message/image is send though. So I'm not sure what the error message is complaining about. :p  

I'm not using the file node from the example though, I'm usin the http request node. The output is set to "a binary buffer". 

The flow consists of three nodes: 
- inject 
- http request node with the url set to a jpg file http://webserver/snapshot.jpg and output to "a binary buffer"
- send image (matrix) node with content type set to "image/jpg". Same issue if I leave the content type empty though.

Like I said, it works, I receive the image, it is just the error in the debug window. 

If you need any further information, please let me know :)

**Comment by skylord123** [comment]
Looks like `matrix-js-sdk` updated and broke this.

This will be fixed in the next release, thanks @hillbicks :)

**Comment by skylord123** [comment]
@hillbicks Just released `0.4.6` that fixes this. Give it a try and let me know if it works :)

**Comment by hillbicks** [comment]
Thanks for the quick fix, that solved the issue. Closing.
