### ISSUE TITLE
Feature request: Delete Messages

### ISSUE THREAD

**Issue by kitzler-walli** [Skylar-Tech/node-red-contrib-matrix-chat#47]
This library is great as it is, but would be awesome if we could delete messages with it.
I think of a use case where I send a message and delete it a few seconds/minutes later.

**Comment by skylord123** [comment]
You are right, this should be added I will make sure it's on the next release.

Currently you can still redact messages it's just a little more complicated:
- Make sure `Global Access To Matrix Client` is turned on in your matrix server config
- Under examples in this repository there is one called [Use function node to run any command](https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/tree/master/examples#use-function-node-to-run-any-command) and it is actually an example of how to redact messages. Any message passed to the input of the function node in that example will be redacted (or just set `msg.event_id` of the event you want redacted)

Once I get a redact node added it will work pretty much the same as that example flow so if you use that in the mean time upgrading later will be really easy. You will just replace the function node with the official node at that point.

**Comment by skylord123** [comment]
This has now been added in `0.5.8` that just dropped today.
