### ISSUE TITLE
No support for receiving m.video messages

### ISSUE THREAD

**Issue by dbutti** [Skylar-Tech/node-red-contrib-matrix-chat#68]
It should be possible to receive messages of type "m.video". This type is currently not supported, and corresponding messages are simply ignored by the receive node.

**Comment by dbutti** [comment]
Just answering to myself... in fact all that is needed is to apply the very same logic which is used for "m.image".

For example, I have patched like this lines 98:101 in src/matrix_receive.js 👍 
`case 'm.image':                                                                                       
                case 'm.video':                                                    
                    if(!node.acceptImages) return;
                    msg.filename = msg.content.filename || msg.content.body;  `

and video media files are handled correctly the same way images do.

**Comment by skylord123** [comment]
This has been added, thanks!
